services:
  - type: web
    name: secure-email-system
    env: python
    buildCommand: "pip install -r requirements.txt && python setup.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
