services:
  - type: web
    name: secure-email-system
    env: python
    buildCommand: "pip install -r requirements.txt && python setup.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: secure-email-db
          property: connectionString

databases:
  - name: secure-email-db
    databaseName: secure_email_db
    user: secure_email_user
    plan: free
